### PR TITLE
use singular for output name `subnet_name`

### PR DESCRIPTION
**Pull request by taoufik07**

### CODE REVIEW

**Review by rossifumax — APPROVED** [review]
Thanks for your contribution ! :slightly_frowning_face:

**Review by BzSpi — APPROVED** [review]

**Comment by Shr3ps** [comment]
Thanks!
I rebased your fix, you can now fix the CI 😸

**Review by Shr3ps — CHANGES_REQUESTED** [review]
You need to update CHANGELOG.md and README files :)

**Comment by taoufik07** [comment]
Amazing! We have CI now 😄 🚀 

@Shr3ps It should be good!

**Review by Shr3ps — APPROVED** [review]

**Pull request merged**
